version: '3.8'

services:
    greenplum_6.8:
      container_name: greenplum
      ports:
        - "5432:5432"
      image: datagrip/greenplum:6.8
      privileged: true
      security_opt:
       - seccomp:unconfined
      healthcheck:
        test: grep -r -i --include \*.log "Database successfully started" || exit 1
